export const SUPABASE_ANON_KEY = "POINT_ENV_VAR_HERE"
export const SUPABASE_PROJECT_URL = "POINT_ENV_VAR_HERE" //NOTE: if you change this, change url in forge.config.js too!!
export const PUSHER_API_KEY = "POINT_ENV_VAR_HERE"

export const PSDK_STATUS_CODES = {
    SUCCESS : 0,
    GENERAL_ERROR : -1,
    DEVICE_NOT_FOUND : -2,
    DEVICE_NOT_READY : -3,
    DEVICE_CONNECTION_FAILED : -4,
    DEVICE_CONNECTION_LOST : -5,
    DEVICE_BUSY : -6,
    DEVICE_WARNING : -7,
    DEVICE_ERROR : -8,
    DEVICE_REJECTED_PAIRING : -9,
    NOT_ALLOWED : -10,
    CANCELLED : -11,
    ABORTED : -12,
    REAUTHENTICATION_REQUIRED : -13,
    CONTACT_ACQUIRER : -14,
    INVALID_STATE : -20,
    INVALID_CONFIGURATION : -21,
    INVALID_ARGUMENTS : -22,
    COMMAND_IN_PROGRESS : -23,
    UNSUPPORTED_COMMAND : -24,
    COMMAND_TIMED_OUT : -25,
    CONFIGURATION_REQUIRED : -30,
    MISSING_LISTENER : -31,
    RECEIPT_SUPPORT_REQUIRED : -32,
    CACHED_CONFIGURATION_MISMATCH : -33
}